---
title: "Med and Max SVL comparsion"
output: pdf_document
---

```{r packages,message=FALSE,echo=FALSE}
library(ape);library(caper);library(phytools);library(knitr)
library(dplyr);library(ggplot2);library(picante);library(reshape2)
```

```{r species data entry,echo=F,results='hide'}
# Entrada de dados:
mat2 <- read.table("raw.data_Rhor_JEB.txt",h=T)
```



```{r phylogeny data entry,echo=F,results='hide'}
mat2 <- read.csv("data_med_max.csv",h=T,sep=",")
mat2 <- melt(mat2, id.vars = c("sp", "DF"),
          variable.name = "source", 
          value.name = "SVL")
arvore<-read.tree("amph_2014.tre")
anura<-drop.tip(arvore,as.character(mat2[,1]))             
filo<-(drop.tip(arvore,anura$tip.label))
filo$node.label 
filo$node.label <- makeLabel(filo)$node.label 
c_data_max <- comparative.data(phy=filo,data=filter(mat2,source=="max"),names.col="sp",vcv=T,vcv.dim=3)
c_data_med <- comparative.data(phy=filo,data=filter(mat2,source=="med"),names.col="sp",vcv=T,vcv.dim=3)
```

1. Min-Max Snout-Vent-Length comparison:

Pgls regression (max SVL):
--------------
```{r,results='hold'}
mod_max <- pgls(log10(DF) ~log10(SVL),c_data_max,"ML")
summary(mod_max)

```

Pgls regression (med SVL):
--------------
```{r,results='hold'}
mod_med <- pgls(log10(DF) ~log10(SVL),c_data_med,"ML")
summary(mod_med)

```

Os coeficientes são ligeiramente diferentes entre os dois modelos. No modelo com tamanho corpóreo médio o ß é menor, ou seja, a frequência dominante decai mais rapidamente. O R2 do modelo com SVL_med é maior do que o com o max.


Regression Graphs:
------------------
```{r}
g1 <- ggplot(mat2,aes(y=log10(DF),x=log10(SVL),colour=source))+
          geom_point()+
          geom_smooth(method="lm",se=T);g1
```

